services:
  - type: web
    name: vterm
    runtime: docker
    repo: https://github.com/opendev-labs/vterm
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 4000
